### PR TITLE
Size optimization

### PR DESCRIPTION
**Pull request by yatli**

### CODE REVIEW

**Comment by yatli** [comment]
well no. changing to uint8_t for a lot of places, save = <1KB

**Comment by yatli** [comment]
Probably not worth it.

**Comment by jmamma** [comment]
Thanks @yatli

**Comment by jmamma** [comment]
Our menu system is still consuming a hell of a lot. 

It's around 5KB, probably 3KB wasted.

```
 09a0 536c6f74 00000000 00000043 4841494e  Slot.......CHAIN
 09b0 3a000000 00000000 00010403 c8610000  :............a..
 09c0 00000141 55540000 00000000 00000002  ...AUT..........
 09d0 4d414e00 00000000 00000000 03524e44  MAN..........RND
 09e0 00000000 00000000 00000000 00000000  ................
 09f0 00000000 00000000 00000000 00000000  ................
 0a00 00000000 00000000 00000000 00000000  ................
 0a10 4c4f4f50 3a202000 00000000 00000040  LOOP:  ........@
 0a20 00593b00 00000000 00000000 00000000  .Y;.............
 0a30 00000000 00000000 00000000 00000000  ................
 0a40 00000000 00000000 00000000 00000000  ................
 0a50 00000000 00000000 00000000 00000000  ................
 0a60 00000000 00000000 00000000 00000000  ................
 0a70 00000000 00524f57 3a202020 20000000  .....ROW:    ...
 0a80 00000000 8000583b 00000000 00000000  ......X;........
 0a90 00000000 00000000 00000000 00000000  ................
 0aa0 00000000 00000000 00000000 00000000  ................
 0ab0 00000000 00000000 00000000 00000000  ................
 0ac0 00000000 00000000 00000000 00000000  ................
 0ad0 00000000 00000000 0000434c 4541523a  ..........CLEAR:
 0ae0 00000000 00000000 000202e1 3c000000  ............<...
 0af0 00002d2d 00000000 00000000 00000159  ..--...........Y
 0b00 45530000 00000000 00000000 00000000  ES..............
 0b10 00000000 00000000 00000000 00000000  ................
 0b20 00000000 00000000 00000000 00000000  ................
 0b30 00000000 00000000 00000000 00000043  ...............C
 0b40 4f50593a 00000000 00000000 00000202  OPY:............
 0b50 e33c0000 0000002d 2d000000 00000000  .<.....--.......
 0b60 00000001 59455300 00000000 00000000  ....YES.........
 0b70 00000000 00000000 00000000 00000000  ................
 0b80 00000000 00000000 00000000 00000000  ................
 0b90 00000000 00000000 00000000 00000000  ................
 0ba0 00000000 50415354 453a0000 00000000  ....PASTE:......
 0bb0 00000002 02e43c00 00000000 2d2d0000  ......<.....--..
 0bc0 00000000 00000000 01594553 00000000  .........YES....
 0bd0 00000000 00000000 00000000 00000000  ................
 0be0 00000000 00000000 00000000 00000000  ................
 0bf0 00000000 00000000 00000000 00000000  ................
 0c00 00000000 00000000 0052454e 414d4500  .........RENAME.
 0c10 00000000 00000000 00000000 0000347f  ..............4.
 0c20 00000000 00000000 00000000 00000000  ................
 0c30 00000000 00000000 00000000 00000000  ................
 0c40 00000000 00000000 00000000 00000000  ................
 0c50 00000000 00000000 00000000 00000000  ................
 0c60 00000000 00000000 00000000 0000ae01  ................
 0c70 00005354 50000000 00000000 00434c45  ..STP........CLE
 0c80 41523a00 00000000 00000000 02028c36  AR:............6
 0c90 00004401 002d2d00 00000000 00000000  ..D..--.........
 0ca0 00014c43 4b530000 00000000 00000000  ..LCKS..........
 0cb0 00000000 00000000 00000000 00000000  ................
 0cc0 00000000 00000000 00000000 00000000  ................
 0cd0 00000000 00000000 00000000 00000000  ................
 0ce0 0000434f 50592053 54455000 00000000  ..COPY STEP.....
 0cf0 00000000 000000ec 01000000 00000000  ................
 0d00 00000000 00000000 00000000 00000000  ................
 0d10 00000000 00000000 00000000 00000000  ................
 0d20 00000000 00000000 00000000 00000000  ................
 0d30 00000000 00000000 00000000 00000000  ................
 0d40 00000000 00000050 41535445 20535445  .......PASTE STE
 0d50 50000000 00000000 00000000 3a010000  P...........:...
 0d60 00000000 00000000 00000000 00000000  ................
 0d70 00000000 00000000 00000000 00000000  ................
 0d80 00000000 00000000 00000000 00000000  ................
 0d90 00000000 00000000 00000000 00000000  ................
 0da0 00000000 00000000 00000000 4d555445  ............MUTE
 0db0 20535445 50000000 00000000 00000000   STEP...........
 0dc0 00a00100 00000000 00000000 00000000  ................
 0dd0 00000000 00000000 00000000 00000000  ................
 0de0 00000000 00000000 00000000 00000000  ................
 0df0 00000000 00000000 00000000 00000000  ................
 0e00 00000000 00000000 00000000 00000000  ................
 0e10 009c0100 00534551 00000000 00000000  .....SEQ........
 0e20 41525045 47494154 4f523a00 00000000  ARPEGIATOR:.....
 0e30 00000087 a1000000 00000000 00000000  ................
 0e40 00000000 00000000 00000000 00000000  ................
 0e50 00000000 00000000 00000000 00000000  ................
 0e60 00000000 00000000 00000000 00000000  ................
 0e70 00000000 00000000 00000000 00000000  ................
 0e80 00000000 00545241 434b2053 454c3a00  .....TRACK SEL:.
 0e90 00000001 11000122 00004c01 00000000  ......."..L.....
 0ea0 00000000 00000000 00000000 00000000  ................
 0eb0 00000000 00000000 00000000 00000000  ................
 0ec0 00000000 00000000 00000000 00000000  ................
 0ed0 00000000 00000000 00000000 00000000  ................
 0ee0 00000000 00000000 0000434f 50593a00  ..........COPY:.
 0ef0 00000000 00000000 00030391 360000c8  ............6...
 0f00 01002d2d 00000000 00000000 00000154  ..--...........T
 0f10 524b0000 00000000 00000002 414c4c00  RK..........ALL.
 0f20 00000000 00000000 00000000 00000000  ................
 0f30 00000000 00000000 00000000 00000000  ................
 0f40 00000000 00000000 00000000 00000043  ...............C
 0f50 4c454152 3a000000 00000000 00000303  LEAR:...........
 0f60 90360000 7801002d 2d000000 00000000  .6..x..--.......
 0f70 00000001 54524b00 00000000 00000000  ....TRK.........
 0f80 02414c4c 00000000 00000000 00000000  .ALL............
 0f90 00000000 00000000 00000000 00000000  ................
 0fa0 00000000 00000000 00000000 00000000  ................
 0fb0 00000000 434c4541 523a0000 00000000  ....CLEAR:......
 0fc0 00000003 03903600 00920100 2d2d0000  ......6.....--..
 0fd0 00000000 00000000 014c434b 53000000  .........LCKS...
 0fe0 00000000 0002414c 4c000000 00000000  ......ALL.......
 0ff0 00000000 00000000 00000000 00000000  ................
 1000 00000000 00000000 00000000 00000000  ................
 1010 00000000 00000000 00504153 54453a00  .........PASTE:.
 1020 00000000 00000000 03038f36 0000ba01  ...........6....
 1030 002d2d00 00000000 00000000 00015452  .--...........TR
 1040 4b000000 00000000 00000241 4c4c0000  K..........ALL..
 1050 00000000 00000000 00000000 00000000  ................
 1060 00000000 00000000 00000000 00000000  ................
 1070 00000000 00000000 00000000 00005452  ..............TR
 1080 41434b20 5245533a 00000000 01030200  ACK RES:........
 1090 220000e0 01013278 00000000 00000000  ".....2x........
 10a0 00000231 78000000 00000000 00000000  ...1x...........
 10b0 00000000 00000000 00000000 00000000  ................
 10c0 00000000 00000000 00000000 00000000  ................
 10d0 00000000 00000000 00000000 00000000  ................
 10e0 00000053 48494654 3a000000 00000000  ...SHIFT:.......
 10f0 00000505 8e360000 e401002d 2d000000  .....6.....--...
 1100 00000000 00000001 4c000000 00000000  ........L.......
 1110 00000000 02520000 00000000 00000000  .....R..........
 1120 00034c3e 414c4c00 00000000 00000452  ..L>ALL........R
 1130 3e414c4c 00000000 00000000 00000000  >ALL............
 1140 00000000 00000000 52455645 5253453a  ........REVERSE:
 1150 00000000 00000003 038d3600 00460100  ..........6..F..
 1160 2d2d0000 00000000 00000000 0154524b  --...........TRK
 1170 00000000 00000000 0002414c 4c000000  ..........ALL...
 1180 00000000 00000000 00000000 00000000  ................
 1190 00000000 00000000 00000000 00000000  ................
 11a0 00000000 00000000 00000000 00cc0100  ................
 11b0 0046494c 45000000 00000000 4e455720  .FILE.......NEW 
 11c0 4449522e 00000000 00000000 00000000  DIR.............
 11d0 00000000 00000000 00000000 00000000  ................
 11e0 00000000 00000000 00000000 00000000  ................
 11f0 00000000 00000000 00000000 00000000  ................
 1200 00000000 00000000 00000000 00000000  ................
 1210 00000000 00000000 00000000 00000000  ................
 1220 0044454c 45544500 00000000 00000000  .DELETE.........
 1230 00000000 00000000 00000000 00000000  ................
 1240 00000000 00000000 00000000 00000000  ................
 1250 00000000 00000000 00000000 00000000  ................
 1260 00000000 00000000 00000000 00000000  ................
 1270 00000000 00000000 00000000 00000000  ................
 1280 00000000 00005245 4e414d45 00000000  ......RENAME....
 1290 00000000 00000000 00000000 00000000  ................
 12a0 00000000 00000000 00000000 00000000  ................
 12b0 00000000 00000000 00000000 00000000  ................
 12c0 00000000 00000000 00000000 00000000  ................
 12d0 00000000 00000000 00000000 00000000  ................
 12e0 00000000 00000000 0000004f 56455257  ...........OVERW
 12f0 52495445 00000000 00000000 00000000  RITE............
 1300 00000000 00000000 00000000 00000000  ................
 1310 00000000 00000000 00000000 00000000  ................
 1320 00000000 00000000 00000000 00000000  ................
 1330 00000000 00000000 00000000 00000000  ................
 1340 00000000 00000000 00000000 00000000  ................
 1350 43414e43 454c0000 00000000 00000000  CANCEL..........
 1360 00000000 00000000 00000000 00000000  ................
 1370 00000000 00000000 00000000 00000000  ................
 1380 00000000 00000000 00000000 00000000  ................
 1390 00000000 00000000 00000000 00000000  ................
 13a0 00000000 00000000 00000000 00000000  ................
 13b0 00000000 00000000 0052414d 20504147  .........RAM PAG
 13c0 45000000 4c494e4b 3a000000 00000000  E...LINK:.......
 13d0 00000002 02cc6100 00000000 4d4f4e4f  ......a.....MONO
 13e0 00000000 00000000 01535445 52454f00  .........STEREO.
 13f0 00000000 00000000 00000000 00000000  ................
 1400 00000000 00000000 00000000 00000000  ................
 1410 00000000 00000000 00000000 00000000  ................
 1420 00000000 00000000 00000000 00535953  .............SYS
 1430 54454d00 00000000 44495350 4c41593a  TEM.....DISPLAY:
 1440 00000000 00000002 02c06100 00000000  ..........a.....
 1450 494e5400 00000000 00000000 01494e54  INT..........INT
 1460 2b455854 00000000 00000000 00000000  +EXT............
 1470 00000000 00000000 00000000 00000000  ................
 1480 00000000 00000000 00000000 00000000  ................
 1490 00000000 00000000 00000000 00534352  .............SCR
 14a0 45454e53 41564552 3a000000 0202c161  EENSAVER:......a
 14b0 00000000 004f4646 00000000 00000000  .....OFF........
 14c0 00014f4e 00000000 00000000 00000000  ..ON............
 14d0 00000000 00000000 00000000 00000000  ................
 14e0 00000000 00000000 00000000 00000000  ................
 14f0 00000000 00000000 00000000 00000000  ................
 1500 0000bab9 00004348 41494e00 00000000  ......CHAIN.....
 1510 00434841 494e3a00 00000000 00000001  .CHAIN:.........
 1520 0403c861 00000000 01415554 00000000  ...a.....AUT....
 1530 00000000 00024d41 4e000000 00000000  ......MAN.......
 1540 00000352 4e440000 00000000 00000000  ...RND..........
 1550 00000000 00000000 00000000 00000000  ................
 1560 00000000 00000000 00000000 00000000  ................
 1570 00000000 00005241 4e44204d 494e3a00  ......RAND MIN:.
 1580 00000000 008000c9 61000000 00000000  ........a.......
 1590 00000000 00000000 00000000 00000000  ................
 15a0 00000000 00000000 00000000 00000000  ................
 15b0 00000000 00000000 00000000 00000000  ................
 15c0 00000000 00000000 00000000 00000000  ................
 15d0 00000000 00000000 00000052 414e4420  ...........RAND 
 15e0 4d41583a 00000000 00008000 ca610000  MAX:.........a..
 15f0 00000000 00000000 00000000 00000000  ................
 1600 00000000 00000000 00000000 00000000  ................
 1610 00000000 00000000 00000000 00000000  ................
 1620 00000000 00000000 00000000 00000000  ................
 1630 00000000 00000000 00000000 00000000  ................
 1640 bab90000 4d440000 00000000 00000054  ....MD.........T
 1650 5241434b 2053454c 4543543a 00000202  RACK SELECT:....
 1660 cd610000 0000004d 414e0000 00000000  .a.....MAN......
 1670 00000001 4155544f 00000000 00000000  ....AUTO........
 1680 00000000 00000000 00000000 00000000  ................
 1690 00000000 00000000 00000000 00000000  ................
 16a0 00000000 00000000 00000000 00000000  ................
 16b0 00000000 4e4f524d 414c495a 453a0000  ....NORMALIZE:..
 16c0 00000002 02cb6100 00000000 4f464600  ......a.....OFF.
 16d0 00000000 00000000 01415554 4f000000  .........AUTO...
 16e0 00000000 00000000 00000000 00000000  ................
 16f0 00000000 00000000 00000000 00000000  ................
 1700 00000000 00000000 00000000 00000000  ................
 1710 00000000 00000000 00435452 4c204348  .........CTRL CH
 1720 414e3a00 00000000 1202bb61 00000000  AN:........a....
 1730 00494e54 00000000 00000000 00114f4d  .INT..........OM
 1740 4e490000 00000000 00000000 00000000  NI..............
 1750 00000000 00000000 00000000 00000000  ................
 1760 00000000 00000000 00000000 00000000  ................
 1770 00000000 00000000 00000000 0000504f  ..............PO
 1780 4c592043 4f4e4649 47000000 00000000  LY CONFIG.......
 1790 00326100 00000000 00000000 00000000  .2a.............
 17a0 00000000 00000000 00000000 00000000  ................
 17b0 00000000 00000000 00000000 00000000  ................
 17c0 00000000 00000000 00000000 00000000  ................
 17d0 00000000 00000000 00000000 00000000  ................
 17e0 00000053 44204452 49564500 00000000  ...SD DRIVE.....
 17f0 00000000 000099a1 00000000 00000000  ................
 1800 00000000 00000000 00000000 00000000  ................
 1810 00000000 00000000 00000000 00000000  ................
 1820 00000000 00000000 00000000 00000000  ................
 1830 00000000 00000000 00000000 00000000  ................
 1840 00000000 00000000 bab90000 4d494449  ............MIDI
 1850 00000000 00000054 5552424f 20313a00  .......TURBO 1:.
 1860 00000000 00000404 89610000 00000031  .........a.....1
 1870 78000000 00000000 00000001 32780000  x...........2x..
 1880 00000000 00000000 02347800 00000000  .........4x.....
 1890 00000000 00033878 00000000 00000000  ......8x........
 18a0 00000000 00000000 00000000 00000000  ................
 18b0 00000000 00000000 00000000 54555242  ............TURB
 18c0 4f20323a 00000000 00000004 048a6100  O 2:..........a.
 18d0 00000000 31780000 00000000 00000000  ....1x..........
 18e0 01327800 00000000 00000000 00023478  .2x...........4x
 18f0 00000000 00000000 00000338 78000000  ...........8x...
 1900 00000000 00000000 00000000 00000000  ................
 1910 00000000 00000000 00000000 00000000  ................
 1920 00434c4b 20524543 3a000000 00000000  .CLK REC:.......
 1930 02028c61 00000000 004d4944 49203100  ...a.....MIDI 1.
 1940 00000000 00014d49 44492032 00000000  ......MIDI 2....
 1950 00000000 00000000 00000000 00000000  ................
 1960 00000000 00000000 00000000 00000000  ................
 1970 00000000 00000000 00000000 00000000  ................
 1980 00000000 0000434c 4b205345 4e443a00  ......CLK SEND:.
 1990 00000000 0002028b 61000000 00004f46  ........a.....OF
 19a0 46000000 00000000 0000014d 49444920  F..........MIDI 
 19b0 32000000 00000000 00000000 00000000  2...............
 19c0 00000000 00000000 00000000 00000000  ................
 19d0 00000000 00000000 00000000 00000000  ................
 19e0 00000000 00000000 0000004d 49444920  ...........MIDI 
 19f0 4657443a 00000000 00000303 c6610000  FWD:.........a..
 1a00 0000004f 46460000 00000000 00000001  ...OFF..........
 1a10 312d3e32 00000000 00000000 02322d3e  1->2.........2->
 1a20 31000000 00000000 00000000 00000000  1...............
 1a30 00000000 00000000 00000000 00000000  ................
 1a40 00000000 00000000 00000000 00000000  ................
 1a50 bab90000 474c4f42 414c0000 0000004c  ....GLOBAL.....L
 1a60 4f414420 50524f4a 45435400 00000000  OAD PROJECT.....
 1a70 0000a7a2 00000000 00000000 00000000  ................
 1a80 00000000 00000000 00000000 00000000  ................
 1a90 00000000 00000000 00000000 00000000  ................
 1aa0 00000000 00000000 00000000 00000000  ................
 1ab0 00000000 00000000 00000000 00000000  ................
 1ac0 00000000 4e455720 50524f4a 45435400  ....NEW PROJECT.
 1ad0 00000000 00000000 004a3f00 00000000  .........J?.....
 1ae0 00000000 00000000 00000000 00000000  ................
 1af0 00000000 00000000 00000000 00000000  ................
 1b00 00000000 00000000 00000000 00000000  ................
 1b10 00000000 00000000 00000000 00000000  ................
 1b20 00000000 00000000 004d4944 49000000  .........MIDI...
 1b30 00000000 00000000 00000000 35a40000  ............5...
 1b40 00000000 00000000 00000000 00000000  ................
 1b50 00000000 00000000 00000000 00000000  ................
 1b60 00000000 00000000 00000000 00000000  ................
 1b70 00000000 00000000 00000000 00000000  ................
 1b80 00000000 00000000 00000000 00004d41  ..............MA
 1b90 4348494e 45445255 4d000000 00000000  CHINEDRUM.......
 1ba0 001aa400 00000000 00000000 00000000  ................
 1bb0 00000000 00000000 00000000 00000000  ................
 1bc0 00000000 00000000 00000000 00000000  ................
 1bd0 00000000 00000000 00000000 00000000  ................
 1be0 00000000 00000000 00000000 00000000  ................
 1bf0 00000043 4841494e 204d4f44 45000000  ...CHAIN MODE...
 1c00 00000000 0000ffa3 00000000 00000000  ................
 1c10 00000000 00000000 00000000 00000000  ................
 1c20 00000000 00000000 00000000 00000000  ................
 1c30 00000000 00000000 00000000 00000000  ................
 1c40 00000000 00000000 00000000 00000000  ................
 1c50 00000000 00000000 41555820 50414745  ........AUX PAGE
 1c60 53000000 00000000 00000050 a4000000  S..........P....
 1c70 00000000 00000000 00000000 00000000  ................
 1c80 00000000 00000000 00000000 00000000  ................
 1c90 00000000 00000000 00000000 00000000  ................
 1ca0 00000000 00000000 00000000 00000000  ................
 1cb0 00000000 00000000 00000000 00535953  .............SYS
 1cc0 54454d00 00000000 00000000 00000000  TEM.............
 1cd0 e4a30000 00000000 00000000 00000000  ................
 1ce0 00000000 00000000 00000000 00000000  ................
 1cf0 00000000 00000000 00000000 00000000  ................
 1d00 00000000 00000000 00000000 00000000  ................
 1d10 00000000 00000000 00000000 00000000  ................
 1d20 00000000 00004155 58205041 47455300  ......AUX PAGES.
 1d30 0052414d 20506167 65000000 00000000  .RAM Page.......
 1d40 00000000 c9a30000 00000000 00000000  ................
 1d50 00000000 00000000 00000000 00000000  ................
 1d60 00000000 00000000 00000000 00000000  ................
 1d70 00000000 00000000 00000000 00000000  ................
 1d80 00000000 00000000 00000000 00000000  ................
```

**Comment by jmamma** [comment]
Not sure if you were aware. 

You can in most cases disable features from MCL firmware to see how much space we save.
(I added this in to strip back the firmware for the MiniCommand.)

MCLMemory.h: rm #define EXT_TRACKS <- remove support for A4 and Ext.

Significant savings.

210056 ->194094

**Comment by yatli** [comment]
Hmmm, but what about the extra midi ports? Grounded?

**Comment by jmamma** [comment]
Because the TI no longer interferes with the MD MID machines. You can sequence external instruments from the MD MID tracks.

We would need to bump up parameter locks from 4 -> 8 for MD tracks to make that work.

**Comment by yatli** [comment]
Current saving = 7KB without feature loss

**Comment by yatli** [comment]
Squeezed another 4KB from the menu option items!
68f5da2 is highly-recommended for cherry-pick, even if this whole branch cannot make it into a merge.

The options are tightly packed and even reused across different menu entries.

**Comment by jmamma** [comment]
> 
> 
> Current saving = 7KB without feature loss

What were the optimizations here? I see a lot of .cpp to .h code movement. 

---

68f5da2 is good.

**Comment by yatli** [comment]
Yeah. Conventionally, inline functions are defined in headers, so that it's pulled into the translation units that include them, and the compiler see them immediately when compiling the individual files, with all -Os passes.

Currently our ALWAYS_INLINED functions defined in implementation files, are not seen immediately by the callers, so the translation units do not see them until link-time optimization (fewer passes). And it doesn't even work if we turn off `-flto`

The main idea is that the linker has less optimization capabilities than the compiler itself, so don't defer optimization to the linker.

**Comment by yatli** [comment]
This is an active issue in the Arduino toolchain that's only resolved recently. See: https://github.com/arduino/Arduino/issues/660

That also explains different sizes under different host platforms and toolchains.

Ideally it shouldn't make a difference if the linker inherits the opt. capabilities from the compiler (e.g. VisualStudio link-time code generation functionality), but until that happens.

**Comment by yatli** [comment]
Alright heading back to the issue.

@jmamma this: https://1drv.ms/x/s!Aql6jSQH9uyZhP1RR_0UWsqnGg_gVw?e=cIIBuV

See the compare-charts sheet.

**Pull request closed without merging**
