### PR TITLE
Midi clock

### PR DESCRIPTION
**Pull request by jmamma**
By counting to 4 instead of 6, 

div128_time = time_for_4_pulses / 8 

which can be calculated by shifting instead of rcall and eliminate floating point operation.

Will probably save 1000 cycles.

### CODE REVIEW

**Comment by jmamma** [comment]
I've lost my faith in ⌛️

**Comment by yatli** [comment]
What's happening? 😯

**Comment by jmamma** [comment]
None of the gear in my studio produces stable clock 😝

**Comment by jmamma** [comment]
We can actually code in MC internal clock if you think this will be useful. 
START/STOP Transport will need to be received from external device, but clock source can be generated internally. 

It's a few lines of code. The functionality is already there.

**Comment by yatli** [comment]
I'd still prefer an external clock -- don't want to have a "tempo page" :D

**Comment by yatli** [comment]
> None of the gear in my studio produces stable clock 😝

`T      i   c         k.` 😅

**Pull request merged**
