### PR TITLE
Force compiler to inline

### PR DESCRIPTION
**Pull request by jmamma**
Compiler optimisations are causing interrupt routines to call external routines.

We should prevent calls to external routines by forcing inline. 

https://github.com/jmamma/MIDICtrl20_MegaCommand/issues/52

### CODE REVIEW

**Comment by jmamma** [comment]
Timer interrupt. Rambank selector is not inlined 😠 

```
00012036 <__vector_32>:
   12036:       1f 92           push    r1
   12038:       0f 92           push    r0
   1203a:       0f b6           in      r0, 0x3f        ; 63
   ...
   ...
   1206a:       00 d0           rcall   .+0             ; 0x1206c <__vector_32+0x36>
   1206c:       1f 92           push    r1
   1206e:       cd b7           in      r28, 0x3d       ; 61
   12070:       de b7           in      r29, 0x3e       ; 62
   12072:       60 e0           ldi     r22, 0x00       ; 0
   12074:       ce 01           movw    r24, r28
   12076:       04 96           adiw    r24, 0x04       ; 4
   12078:       3d df           rcall   .-390           ; 0x11ef4 <_ZN15RamBankSelectorC2Eh.lto_priv.529>
   1207a:       80 91 8b 9a     lds     r24, 0x9A8B     ; 0x809a8b <slowclock>
   1207e:       90 91 8c 9a     lds     r25, 0x9A8C     ; 0x809a8c <slowclock+0x1>
```

**Comment by jmamma** [comment]
inline changes add around 22,908bytes of bloat to program size.

**Comment by jmamma** [comment]
Firmware feels slightly snappier with this patch. 

@yatli when you have a moment. 

I just bought a new CRO, so it might be time to actually measure ISR completion times.

**Comment by yatli** [comment]
I'm trying this together with the space reducing patch. Program space bounces back from 64% to 80%.
Going through the code now.

**Comment by jmamma** [comment]
I was thinking about this earlier. Some of the inlining might be too heavy handed (MidiUartParent.hh for example).

Especially for 22KB of program space loss.

**Comment by yatli** [comment]
I'm trying to find the heavy hitters:

```
MDClass::setTrackParam 46 refs
MDClass::triggerTrack 11 refs
MidiSysexClass::getByte 72 refs (!)
MidiUartParent::sendCC 30 refs
MDSeqTrack::send_trig 14 refs
```

**Comment by yatli** [comment]
Done, that's all of them.
Listing the costs of disabling those.

```
MidiSysexClass::getByte 72 refs ~2%
MDClass::setTrackParam 46 refs 11980bytes ~5% (!) 
MDClass::triggerTrack 4250bytes ~1%
sendCC 0bytes 0% (compiler refuse to inline?)
MDSeqTrack::send_trig 614 bytes ~1%
```

**Comment by jmamma** [comment]
What did you find ?

**Comment by yatli** [comment]
eliminating these heavy hitters reduce about half of the bloat, while the critical stuff (ram bank switching, clock_diff etc.) are still in place

**Comment by jmamma** [comment]
Sorry my browser was not up to date. I see your results now.

**Comment by jmamma** [comment]
Cool. I should be able to write inline versions of the heavy hitter(s) and force functions executed within interrupt routine to use those instead.

**Comment by yatli** [comment]
Yeah, given these routines are more than just one or two cycles, the gained speed/space ratio would not be that much

**Comment by yatli** [comment]
especially `MDClass::setTrackParam` alone takes 12KB :D

**Comment by jmamma** [comment]
before (inlining):
 ../../../../tools/avr/bin/avr-size main.hex
   text	   data	    bss	    dec	    hex	filename
      0	 172374	      0	 172374	  2a156	main.hex

after (inlining):

 ../../../../tools/avr/bin/avr-size main.hex
   text	   data	    bss	    dec	    hex	filename
      0	 180250	      0	 180250	  2c01a	main.hex

**Comment by jmamma** [comment]
param locks not working.

**Comment by jmamma** [comment]
text	   data	    bss	    dec	    hex	filename
      0	 181258	      0	 181258	  2c40a	main.hex

**Comment by jmamma** [comment]
A more space efficient version with more overhead, but only 800 bytes difference.

```
135 void MDSeqTrack::send_parameter_locks(uint8_t step) {
136   uint8_t c;
137   bool lock_mask_step = IS_BIT_SET64(lock_mask, step);
138   bool pattern_mask_step = IS_BIT_SET64(pattern_mask, step);
139 
140   for (c = 0; c < 4; c++) {
141    uint8_t send_param = 255;
142     if (lock_mask_step && pattern_mask_step) {
143         if (locks[c][step] > 0) {
144           send_param = locks[c][step] - 1;
145         } else if (locks_params[c] > 0) {
146           send_param = locks_params_orig[c];
147         }
148     }
149 
150     else if (lock_mask_step) {
151         if (locks[c][step] > 0) {
152           send_param = locks[c][step] - 1;
153         }
154     }
155 
156     else if (pattern_mask_step) {
157 
158         if (locks_params[c] > 0) {
159           send_param = locks_params_orig[c];
160       }
161     }
162     if (send_param != 255) { MD.setTrackParam_inline(track_number, locks_params[c] - 1, send_param); }
163   }
164 }
```

**Pull request merged**
