### PR TITLE
add comments on MidiClock

### PR DESCRIPTION
**Pull request by yatli**
@jmamma I still haven't figured out how the 5KHz timer and MIDI_CLOCK both affects div192th and mod12counter.

### CODE REVIEW

**Comment by jmamma** [comment]
div192 is a intermediate clock event generated at t / 2 , where t = time between midi time pulse.

To get an 'average' time. We calculate the time taken for 8 MIDI pulses then divide by ( 2 * 8 = 16 ) to get the interpolation time.

```
div192_time = diff_clock8 / 16;
```

div96th counter is increased on MIDI clock message. 
div192th counter is increased on MIDI Clock message and when (MidiClock.div196th_countdown >= MidiClock.div196_time);

We always want to use MidiClock signal where we can. Half of the div192 events occur on MidiClock, the other half we use the interpolation time.

```
X=div96
x=div192

X     X     X     X
x  x  x  x  x  x  x
```

**Comment by jmamma** [comment]
Eek. just realised I renamed div192 to div196.

Must have been half asleep.

**Comment by yatli** [comment]
As my MD clock is going crazy I'm now receiving clock from A4.
Is it possible to still use MD to send transport messages (play, stop)?

**Comment by jmamma** [comment]
> As my MD clock is going crazy I'm now receiving clock from A4.
> Is it possible to still use MD to send transport messages (play, stop)?

This feature is not implemented. It would require additional logic in MidiUart.cpp .
Currently transport is linked to same port as clock.

**Review by jmamma — COMMENTED** [review]
I'd like to merge this.

**Pull request merged**
