### PR TITLE
Remove write mode

### PR DESCRIPTION
**Pull request by jmamma**
It's time to say goodbye to write mode.

We will be keeping the basic kit/pattern write functionality in the background for when the sequencer is not running. For instance, using the chain page with sequencer stopped will cause the MD current pattern and kit to be regenerated from the MC.

### CODE REVIEW

**Comment by jmamma** [comment]
Should auto-merge be activated by default -> no longer allowing MD patterns to be restored from the chain/write page.

Should we still try and support "poor man's plus drive".

I'm leaning towards no.

**Comment by yatli** [comment]
>poor man’s plus drive

Let’s make it a menu item then — it’ll be even better than a plusdrive. Access snapshots from an sdcard—how awesome is that ;)

That being said, it’s a low priority thing. No need to put it on a near milestone.

**Comment by jmamma** [comment]
Write mode now removed.

Just need to continue to test that saving/merging and chaining works as expected.

**Comment by jmamma** [comment]
I've merged this branch in to dev.

**Pull request closed without merging**
