### PR TITLE
MegaCom basic framework

### PR DESCRIPTION
**Pull request by yatli**
Work in progress. We can build a lot of things upon this:

```c
enum comserver_id_t {
  COMSERVER_EXTUI, // button input, ext screen etc.
  COMSERVER_FILESERVER, // simple FTP-ish protocol
  COMSERVER_EXTMIDI, // note in, CV out etc.
  COMSERVER_MAX,
  COMSERVER_DRAIN_INVALID = 0xFF
};
```

### CODE REVIEW

**Comment by yatli** [comment]
To eval the idea I'll implement file server and usb midi.

**Comment by jmamma** [comment]
it would be good if the pc side application ran as a vst.

**Comment by yatli** [comment]
> it would be good if the pc side application ran as a vst.

Windows only?

**Comment by jmamma** [comment]
> > it would be good if the pc side application ran as a vst.
> 
> Windows only?

I hope not :grin:

**Comment by yatli** [comment]
Then this: https://juce.com/ ?

**Comment by jmamma** [comment]
Yep. that's what I was thinking.

Been a while since i've looked into vst multi platform tech.

**Comment by jmamma** [comment]
Yep. that's what I was thinking.

Been a while since i've looked into vst multi platform tech.

**Comment by jmamma** [comment]
Yep. that's what I was thinking.

Been a while since i've looked into vst multi platform tech.

**Comment by jmamma** [comment]
Yep. that's what I was thinking.

Been a while since i've looked into vst multi platform tech.

**Comment by jmamma** [comment]
Yep. that's what I was thinking.

Been a while since i've looked into vst multi platform tech.

**Comment by jmamma** [comment]
Yep. that's what I was thinking.

Been a while since i've looked into vst multi platform tech.

**Comment by yatli** [comment]
Did your ISP just accidentally turn the "retrig" knob? :D

**Comment by yatli** [comment]
... or make it a VST host?

MD -> Kit Edit -> scroll down to the VST menu

**Comment by yatli** [comment]
finished the ack/resend/timeout transportation layer.
MegaCom is half-duplex so it's easier than Tcp(
will test with a hello world server tomorrow.

**Comment by yatli** [comment]
couldn't get UART0 RX interrupt to work... thoughts?

**Comment by jmamma** [comment]
The UART0 ISRs are being managed by the Arduino serial libraries.

It's how Serial.begin works.

See:

./HardwareSerial0.cpp

**Comment by jmamma** [comment]
The UART0 ISRs are being managed by the Arduino serial libraries.

It's how Serial.begin works.

See:

./HardwareSerial0.cpp

**Comment by yatli** [comment]
> couldn't get UART0 RX interrupt to work... thoughts?

please disregard. it doesn't work because non of the tools I tried work at 250kbps sending hex (

The arduino serial monitor does allow me to reach the ISR, but no hex input.
The other tools I tried (moserial, YAT, minicom) either doesn't have hex, or doesn't support 250kbps

**Comment by yatli** [comment]
image

Even works when the sequencer is running.
Fully asynchronous.

**Comment by yatli** [comment]
Fact: running the sequencer at the grid page, file download speed = sorta 20KB/s
It gets more bandwidth when opening the setting page and navigate to SYSTEM with only 2 entries displayed, or the CHROMATIC page which is lazily drawn :D :D :D

**Comment by yatli** [comment]
Funny. I got a steady repro of the BPM drifting problem (while transferring file):
- Go to config
- Go to system
- Get back to Grid
- Do it a few times and the BPM raises.

**Comment by jmamma** [comment]
Sounds the like the serial ISR is hogging the cpu not allowing the MIDI or TIMER ISRS to execute.
Lowering the baud will probably solve this.

**Comment by yatli** [comment]
It also raises tempo without file transferring.
What kind of magic is this 🤔

**Comment by jmamma** [comment]
If you don't enable*** all ISR ```sei()``` before the sequencer ISR runs, same thing happens. The tempo increases.
This is likely because the clock counters are not increasing.

So perhaps something similar is happening here?

**Comment by yatli** [comment]
oh ok.  so it's like, something in the menu system blocked the ISR for a bit of time?

**Comment by jmamma** [comment]
Shouldn't be.

The only thing blocking the timer IRSs should be other ISRs or if you explicitly disable interrupts in your code.

**Comment by jmamma** [comment]
Is data hitting UART0 when idle?

**Comment by yatli** [comment]
no. ISR standing by.

**Comment by jmamma** [comment]
you sure?

**Comment by yatli** [comment]
yeah pretty sure. host is doing nothing if I don't click the UI.

**Comment by jmamma** [comment]
My suspicion is that one of your conditional statements is passing unexpectedly and is triggering a call to the ring buffer code that is using USE_LOCK() / SET_LOCK()

--

Or there is continuous data on the UART0 causing the isr to be triggered.

**Comment by yatli** [comment]
Let me try this on the dev branch.

**Comment by yatli** [comment]
That's a repro. dev branch. :p

**Comment by jmamma** [comment]
> 
> 
> That's a repro. dev branch. :p

You seeing tempo drift in dev branch?

**Comment by yatli** [comment]
Yeah. Just do a few rounds of the menu thing.

**Comment by jmamma** [comment]
> 
> 
> Yeah. Just do a few rounds of the menu thing.

do what now?

**Comment by jmamma** [comment]
Just flashed dev branch. I'm not seeing any tempo drift. (from grid page tempo display)

**Comment by yatli** [comment]
- On GridPage, SAVE+WRITE enter menu
- Enter a submenu (the deeper the better)
- Get out with SAVE button, back to GridPage
- Rinse and repeat

**Comment by jmamma** [comment]
When MENU -> MD settings are changed. Global settings are sent back to the MD. This includes tempo.

I think there is an edge case where the global settings tempo, is not up to date, so the MD tempo gets shifted to an older value... instead of current.

**Comment by yatli** [comment]
Not likely. Why does it keep increasing?

**Comment by jmamma** [comment]
I'm not seeing the increase you're reporting then.

**Comment by yatli** [comment]
A simpler repro without involving the GridPage init/cleanup:

- Enter a submenu with WRITE
- Get back with SAVE
- Repeat

**Comment by jmamma** [comment]
Not showing up for me. 

```
Justins-MacBook-Pro-4:megacommand jmammarella$ md5 main.hex
MD5 (main.hex) = bc67731518f844109024bbdf1be6a3c0
Justins-MacBook-Pro-4:megacommand jmammarella$ git status . | head -n 20
On branch dev
Untracked files:
```

```
Justins-MacBook-Pro-4:megacommand jmammarella$ git log | head -n 20
commit cf7b6e5ca351760162b5e785b4dc34a2b6e5e5e2
Merge: 4408431 73dd675
Author: jmamma <jmamma@gmail.com>
Date:   Tue Aug 11 12:36:09 2020 +1000

    Merge pull request #125 from jmamma/size_reduce_2
    
    Size reduce attempt 2
```

**Comment by yatli** [comment]
Alright. Same as the last time I opened the case.
We can discard the issue here I guess.

**Comment by jmamma** [comment]
What happened last time ?

Bad compile ?

**Comment by yatli** [comment]
The timeline:
1. https://github.com/jmamma/MIDICtrl20_MegaCommand/issues/4
2. https://github.com/jmamma/MIDICtrl20_MegaCommand/pull/47#issuecomment-546681967
3. https://github.com/jmamma/MIDICtrl20_MegaCommand/pull/47#issuecomment-546684139
4. https://github.com/jmamma/MIDICtrl20_MegaCommand/issues/65

So, just some weird states going on in my MD. Maybe related to other issues (last time it was https://github.com/jmamma/MIDICtrl20_MegaCommand/issues/98)

**Comment by yatli** [comment]
Porting https://github.com/v-yadli/paw-01 over to test realtime messages.

**Comment by jmamma** [comment]
What is/was paw-01?

**Comment by yatli** [comment]
Oh that.

image

image

**Comment by yatli** [comment]
image

A synth that browses the internet(

**Comment by jmamma** [comment]
Is that a DAW or a 💣?

**Comment by yatli** [comment]
which red wire again?

**Comment by yatli** [comment]
Took me quite a while to make it stable and not dropping frames, but here it is, a 1x2 midi bridge.

Host: https://github.com/yatli/Camelotia/tree/main/src/MegaCom.MidiHost

Requires two virtual midi devices, "MegaCommandPort1" and "MegaCommandPort2"

**Comment by yatli** [comment]
Also, debug messages are framed into one kind of message. So the debugging capabilities can be retained (or even improved)

**Comment by yatli** [comment]
With megacom framed debug (and custom formatter):
Sketch uses 221460 bytes (87%) of program storage space. Maximum is 253952 bytes.

With standard Serial.print, upstream `dev` branch:
Sketch uses 218962 bytes (86%) of program storage space. Maximum is 253952 bytes.

(Cannot compile megacom-enabled debug version with Serial because of uart0 conflicts)

**Comment by yatli** [comment]
Hook up the midi host and debug:

image

**Comment by jmamma** [comment]
Cool. I had always wanted to replace Serial.print with something more robust. 
DisplayMirror mode will need to be implemented using this new protocol.

**Comment by yatli** [comment]
I've never used that mode.
With the new GUI (cross platform, rest assured) in place I guess it's the time.

**Comment by yatli** [comment]
Thinking of putting a MC into this:

image

```
int MCDisplayServer::run() {
  // TODO external key, knobs etc. events handling
  return -1;
}
```

**Comment by yatli** [comment]
```c++
void MCUIServer::update() {
  megacom_task.tx_begin(COMCHANNEL_UART_USB, COMSERVER_EXTUI, 513);
  megacom_task.tx_data(COMCHANNEL_UART_USB, USC_DRAW);
  megacom_task.tx_vec(COMCHANNEL_UART_USB, (char*)oled_display.getBuffer(), 512);
  megacom_task.tx_end(COMCHANNEL_UART_USB);
}
```

**Comment by yatli** [comment]
Some progress on the UI. Decoupled the Camelotia stuff and add multiple tabs:

image

**Comment by yatli** [comment]
Debug view ready:
image

**Comment by yatli** [comment]
Display mirror ready:

image

Too easy.

**Comment by jmamma** [comment]
😮 
Great work.

Any chance for easy .png screenshot export, and support for inverse colour mode. That's how I generate screenshots for the manual.

**Comment by yatli** [comment]
Done.

image

**Comment by yatli** [comment]
The OLED emulation is actually an aliasing artifact. Don't know exactly how to repro that when rendering to a PNG 😅

**Comment by jmamma** [comment]
beautiful work. thankyou

**Comment by yatli** [comment]
The framework is ready now. @jmamma 
What about the UI? Do we want to add it to this repo?

**Comment by jmamma** [comment]
Which UI?

**Comment by yatli** [comment]
https://github.com/yatli/MegaCom.UI
ignore the README.

**Comment by jmamma** [comment]
gotcha. keep repo separate is probably better.

**Comment by yatli** [comment]
Understood.

Currently it has the following functionalities:

- File Browser (wip, only CWD, GET, LS implemented)
- Debug, with improved macros. Things like DEBUG_PRINTLN now takes arbitrarily many arguments, and printed atomically.
- Midi proxy: Midi bridge into 2 virtual midi devices.
- Display Mirror, with throttle control.

**Comment by yatli** [comment]
You're on macOS? Let me build a package for you.

**Comment by jmamma** [comment]
either mac or pc.

**Comment by yatli** [comment]
PC: https://yadli.net/index.php/s/d7x3f7sBDtJNc2N
mac: https://yadli.net/index.php/s/w7AFLEfrqQCPq9G

**Comment by yatli** [comment]
A nice little speed meter: 
image

**Comment by albadort76** [comment]
> Thinking of putting a MC into this:
> 
> image
> 
> ```
> int MCDisplayServer::run() {
>   // TODO external key, knobs etc. events handling
>   return -1;
> }
> ```

i got one PT80 at home, would be so fun to have an MC inside! :)

**Pull request closed without merging**
