### PR TITLE
seqpage/pageselectpage TI led

### PR DESCRIPTION
**Pull request by yatli**
Requires https://github.com/yatli/mdhack/pull/20

Demonstrates two TI trigled modes: normal and rec.

PageSelectPage uses the normal mode to show the current selected page. Playing notes will be displayed on the TI.
SeqPage uses the rec mode to show MCL mask data plus the current playing cursor.

### CODE REVIEW

**Comment by jmamma** [comment]
Just testing this out now.

The latency is much improved. ~still a few ms delay on the MD side. But good enough for now.~

There is a bug, if you enable REC on the MD. you will input step sequencer data on the MD sequencer, without seeing it visually.

**Comment by jmamma** [comment]
Can we re-name REC mode to something else. STEPINPUT perhaps ?

**Comment by jmamma** [comment]
~In "REC" mode we need to show the current selected trigs, in addition to the trig mask.~
Because the SET_BIT64() is set on trig release, there is perceived lag on the MD side.

Edit: i think we just need to mimic the MD step edit behaviour more closely.
If the note has no trig, then set trig regardless of "hold_time"

**Comment by jmamma** [comment]
~Trig Latency appears to also be present in the MD's standard step edit mode.~

I think this is just my worn out MD triggers. Tested against my 'backup' MD and the response is the same.

**Comment by jmamma** [comment]
9725f5d

Step input should feel more responsive now. Step will be set if empty on press.

**Comment by jmamma** [comment]
We should disable MD step edit mode if in MCL step edit mode.

**Comment by yatli** [comment]
> There is a bug, if you enable REC on the MD. you will input step sequencer data on the MD sequencer, without seeing it visually.

This is because currently our TI hack only handles the non rec mode path.
We can setup a MCL presence flag in the FW, and disable the MD step edit accordingly.

Then we can use the MD rec button to enter the MCL step edit mode?

**Comment by jmamma** [comment]
> Then we can use the MD rec button to enter the MCL step edit mode?

I thought about this. but it might not be desirable. For instance I regularly find myself in the MD step edit mode with the MC attached.

--

Just noticed that MUTE step leds are now broken too when in MCL step edit. Same issue as above.

**Comment by yatli** [comment]
Makes sense. I'll think about the precedence and override rules.

**Comment by yatli** [comment]
@jmamma 

```c++
  // Do not show stepedit trigled if:
  // - trigger interface is not activated
  // - MD rec mode is activated
  // - MD bank selection is activated
  // - MD seq edit (mute, slide etc.) is activated
  if (BankButtonPressIndexForPopup >= 0  ||
      md_menu_cmd.md_menu_cmd5 != RecordDeactivated || 
      md_menu_cmd.md_menu_cmd4 != 0 ||
      !trigger_interface_en){
    return LEDS_dynamic[i] ^ LEDS_static[i];
  }
```

**Comment by jmamma** [comment]
> @jmamma
> 
> ```c++
>   // Do not show stepedit trigled if:
>   // - trigger interface is not activated
>   // - MD rec mode is activated
>   // - MD bank selection is activated
>   // - MD seq edit (mute, slide etc.) is activated
>   if (BankButtonPressIndexForPopup >= 0  ||
>       md_menu_cmd.md_menu_cmd5 != RecordDeactivated || 
>       md_menu_cmd.md_menu_cmd4 != 0 ||
>       !trigger_interface_en){
>     return LEDS_dynamic[i] ^ LEDS_static[i];
>   }
> ```

does this work?

**Comment by yatli** [comment]
https://github.com/yatli/mdhack/pull/20/commits/727de6923811a3930e10034fdef04b293336e6a7

Try the latest one.
When MD rec mode is active, the LEDs display the internal sequencer state (same for mute/accent etc.)

**Comment by yatli** [comment]
It even works with bank selection. When the popup times out, the stepedit TI comes back online :D

**Comment by yatli** [comment]
Only issue, MD does not know the MC step cursor position. I'm currently using the internal sequencer step cursor.

Can we sync the SCALE SETUP over from MC?

**Comment by yatli** [comment]
Tried more patterns with the PageSelectPage TI led index indicator -- maybe we should go exclusive instead of overlay

**Comment by yatli** [comment]
Overlay leds for chain/write indicator would be fun. I can then see which tracks are playing notes and chain those.

**Comment by jmamma** [comment]
> Only issue, MD does not know the MC step cursor position. I'm currently using the internal sequencer step cursor.
> 
> Can we sync the SCALE SETUP over from MC?

Yeah that would be awesome. I found myself trying to change the current "page" of the sequence using the scale button on the MD. Only to remember i had to do in the MC.

**Comment by jmamma** [comment]
this is really good now.

**Comment by jmamma** [comment]
We need another mode. to hide the sequencer events.

For example, it's hard to see the current page select, when the sequencer is running

---

And we need a mode, to prevent XOR from sequencer events. 

So if you hold down trigs, the sequencer events don't XOR the held trigs.

test commit below to see behaviour:

**Comment by yatli** [comment]
see https://github.com/jmamma/MIDICtrl20_MegaCommand/pull/123/commits/3e3f9426533e0481c9e23cdb7f73a33751130ac4

**Comment by yatli** [comment]
PageSelectPage not sending the first leds update
edit: fixed.

**Comment by jmamma** [comment]
> 
> 
> see [3e3f942](https://github.com/jmamma/MIDICtrl20_MegaCommand/commit/3e3f9426533e0481c9e23cdb7f73a33751130ac4)

need the patch on the MD side.

**Comment by yatli** [comment]
Forgot to commit...

https://github.com/yatli/mdhack/pull/20/commits/6bb64b040476a41c2b4de934630dc780b9c7d587

**Comment by jmamma** [comment]
> 
> 
> Forgot to commit...
> 
> [yatli/mdhack@6bb64b0](https://github.com/yatli/mdhack/commit/6bb64b040476a41c2b4de934630dc780b9c7d587)

yep that's perfect.

--

Now just the issue of the step indicator.
This will be broken for track speeds and different track lengths.

**Comment by yatli** [comment]
merging this one for cleaner code review on https://github.com/jmamma/MIDICtrl20_MegaCommand/pull/124

**Pull request merged**
