### PR TITLE
Add appegiator to Chromatic Page

### PR DESCRIPTION
**Pull request by jmamma**
Been meaning to add this for a while.

Basic functionality is working.

Need to create a GUI popup page for it accessible from Track Menu on SeqPtcPage.

### CODE REVIEW

**Comment by yatli** [comment]
I listened to the demo. Awesome!!

**Comment by jmamma** [comment]
@yatli the arp functionality is done. 

have  a play. 

my favourite mode right now is  LATCH + RND.

**Comment by jmamma** [comment]
merged in to dev.

**Comment by yatli** [comment]
Are we still using the master-dev paradigm? I'll rebase the samplemgr PR if so.

**Comment by jmamma** [comment]
> 
> 
> Are we still using the master-dev paradigm? I'll rebase the samplemgr PR if so.

yes.

**Pull request closed without merging**
